[build]
  base = "/"
  command = "npm run build"
  publish = "out/"
  [build.environment]
    NODE_VERSION = "24"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=2592000,
    s-maxage=2592000'''
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
